name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Convert post markdown -> html
        run: npm run build

      - name: Copy public files to droplet
        uses: up9cloud/action-rsync@v1.4
        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ secrets.DEPLOY_USER }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          ARGS: -az --chown=www-data:www-data
          SOURCE: ./public/
          TARGET: /srv/httpd/html/
          VERBOSE: true
          PRE_SCRIPT: |
            echo "Starting at: "$(date -u)
          POST_SCRIPT: |
            echo "Completed at: "$(date -u)

#  deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up SSH
#        uses: webfactory/ssh-agent@v0.5.0
#        with:
#          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
#
#      - name: SSH, Deploy, Convert, Copy
#        run: |
#          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_CONNECTION_STRING }} << 'EOF'
#            echo "Starting deployment..."
#            cd /srv/httpd/website
#
#            echo "Pulling latest code from GitHub..."
#            git pull origin main
#
#            echo "Running conversion of posts: markdown -> html..."
#            npm install
#            npm run build
#
#            echo "Copying files in ./public to web root..."
#            rsync -avz --chown=www-data:www-data --chmod=ug=rwx,o=rx /srv/httpd/website/public/ /srv/httpd/html/
#
#            echo "Deployment complete!"
#          EOF
