name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: npm install

      - name: Convert post markdown -> html
        run: npm run build

      - name: Copy public files to droplet
        uses: up9cloud/action-rsync@v1.4
        env:
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          USER: ${{ secrets.DEPLOY_USER }}
          HOST: ${{ secrets.DEPLOY_HOST }}
          ARGS: -az --chown=www-data:www-data
          SOURCE: ./public/
          TARGET: /srv/httpd/html/
          VERBOSE: true
          PRE_SCRIPT: |
            echo "Starting at: "$(date -u)
          POST_SCRIPT: |
            echo "Completed at: "$(date -u)

      # TODO - may want to add extra steps to copy compose.yaml and other server files
